MAASSER_NOMINAL, MAASSER_PASSWORD_INIT, MAASSER_GIVE_DATE, MAASSER_GIVE_AMOUNT, MAASSER_RECEIVE_DATE,\
 MAASSER_RECEIVE_AMOUNT, MAASSER_VIEW, MAASSER_PERCENTAGE, MAASSER_CURRENCY, MAASSER_CURRENCY_PASSWORD,\
 MAASSER_EDIT, MAASSER_EDIT_HANDLE, MAASSER_GIVE_COMMENT = range(13)
