AUTHENTICATED, ADD, POI_ADD, POI_ADD_INTEREST, POI_ADD_NAME, POI_ADD_DESC, POI_ADD_LOCATION, POI_ADD_ADDRESS,\
    INTEREST_ADD_PARENT, INTEREST_ADD_NAME, EVENT_ADD_HANDLE_CHOICE, EVENT_ADD_INTEREST, EVENT_ADD_NAME,\
    EVENT_ADD_DATE, EVENT_ADD_TIME,  EVENT_ADD_DESC, EVENT_ADD_POI, EVENT_ADD_HANDLE_RECURRENCE = range(18)
